import { Palette, VerticalBox, HorizontalBox, Button } from "std-widgets.slint";

component ESoPeLogo inherits Rectangle {
    VerticalBox {
        height: 59px;
        padding: 0;
        Rectangle {
            background: #cd161b;
            HorizontalBox {
                padding: 0;
                spacing: 0;
                Image {
                    vertical-alignment: bottom;
                    horizontal-alignment: left;
                    source: @image-url("assets/esope_logo_l.png");
                }

                VerticalBox {
                    alignment: end;
                    padding: 0;
                    Rectangle {
                        height: 18px;
                        background: #fff;
                    }
                }
            }
        }
    }
}

component LabeledValue inherits HorizontalBox {
    in property <string> label;
    in property <string> text;

    padding-right: 8px;
    spacing: 3px;
    // width of a space char
    padding: 0;
    Text {
        horizontal-alignment: left;
        text: label;
    }

    Text {
        horizontal-alignment: right;
        text: text;
    }
}

export component AppWindow inherits Window {
    in property <string> version;
    in property <string> runtime_minutes : "00:00"; 
    private property <int> counter;
    
    background: Palette.background.darker(0.1);

    VerticalBox {
        alignment: space-between;
        
        padding: 0;
        spacing: 0;
    
        VerticalBox {
            height: 58px;
            padding: 0;
            alignment: start;
            ESoPeLogo { }
        }

        Rectangle {
            height: 36px;
            Text {
                vertical-alignment: top;
                text: "Slint Demo";
                // font-size: 24px;
            }
        }

        VerticalBox {
            padding-right: 20px;
            padding-left: 20px;
            
            LabeledValue {
                alignment: center;
                label: "Runtime:";
                text: "\{root.runtime_minutes} min";
            }

            LabeledValue {
                alignment: center;
                label: "Counter:";
                text: root.counter;
            }

            Button {        
                clicked => { root.counter += 1 }
                text: "Increase counter";
            }
        }       

        VerticalBox {
            alignment: end;
            padding: 0;
            Text {
                horizontal-alignment: right;
                text: "Version: \{root.version}";
            }
        }

    }
}